### ISSUE TITLE
warning: constant OpenSSL::SSL::SSLContext::METHODS is deprecated

### ISSUE THREAD

**Issue by rajeejones** [rubygems/ruby-ssl-check#1]
I am receiving this line when running the script.

    $ curl -sL https://git.io/vQhWq | ruby
    Here's your Ruby and OpenSSL environment:

    Ruby:           2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
    RubyGems:       2.7.4
    Bundler:        1.16.0
    Compiled with:  OpenSSL 1.0.2n  7 Dec 2017
    Loaded version: OpenSSL 1.0.2n  7 Dec 2017
    SSL_CERT_FILE:  /usr/local/etc/openssl/cert.pem
    SSL_CERT_DIR:   /usr/local/etc/openssl/certs

    With that out of the way, let's see if you can connect to rubygems.org...

    Bundler connection to rubygems.org:       success ✅
    RubyGems connection to rubygems.org:      success ✅
    Ruby net/http connection to rubygems.org: success ✅

    Hooray! This Ruby can connect to rubygems.org. You are all set to use Bundler and RubyGems. 👌
    -:134: warning: constant OpenSSL::SSL::SSLContext::METHODS is deprecated
    $ 
I am trying to see if this is something I should worry about?

**Comment by colby-swandale** [comment]
That warning can be ignored. We'll need to update the script to use the newer method to detect compatibility.

**Comment by rubyFeedback** [comment]
Ah yes, I just wanted to report the same. Found it in some code that checks for older openssl versions installed locally by indirect. :)

**Comment by indirect** [comment]
This should be fixed in dae3acc583c231e7531c074431686e9174c329e9.
