### ISSUE TITLE
Mac OS Monterey returns -:40: uninitialized constant RUBY_REVISION (NameError)

### ISSUE THREAD

**Issue by jenlampton** [rubygems/ruby-ssl-check#12]
Hello, I am following the [instructions on how to do an automated SSL check](https://bundler.io/guides/rubygems_tls_ssl_troubleshooting_guide.html#automated-ssl-check), where they recommend running the command `curl -Lks 'https://git.io/rg-ssl' | ruby` and ask if you see one of two possible outputs: “Your Ruby can’t connect to rubygems.org because you are missing the certificate”  or “Your Ruby can’t connect to rubygems.org because your version of OpenSSL is too old”.

On MacOS Monterey, neither of those happen, instead I see this error:

`-:40: uninitialized constant RUBY_REVISION (NameError)`

**Comment by deivid-rodriguez** [comment]
Hi! Can you share the output of `ruby -v` and `gem env`?

**Comment by jenlampton** [comment]
Sure thing:

> ruby -v 

`ruby 1.8.7 (2009-06-12 patchlevel 174) [i686-darwin10.8.0]`

> gem env

```
RubyGems Environment:
  - RUBYGEMS VERSION: 1.3.5
  - RUBY VERSION: 1.8.7 (2009-06-12 patchlevel 174) [i686-darwin10.8.0]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/1.8
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-darwin-10
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/1.8
     - /Users/jlampton/.gem/ruby/1.8
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://gems.rubyforge.org/
```

My goal here was to update ruby, since I don't think ruby 1.x works on the mac M1 chip, but I'm having a lot of difficulty doing that (since ruby 1 is what's included in xtools?!?!)

**Comment by deivid-rodriguez** [comment]
Ruby 1.8 is so old! Have a look at https://github.com/rbenv/rbenv instead, the Ruby that comes with MacOS does not work very well.

**Comment by duckinator** [comment]
As of #14, if you're using a Ruby version older than 2.7.0 you will get a warning saying the Ruby version you're using is unsupported.

Here's an example for Ruby 2.6.7:

```
!!! WARNING !!!
Ruby 2.6.7 has reached end-of-life, and is unsupported.
This script may not work.
```

(For Ruby 1.8.7, it would say `Ruby 1.8.7` instead of `Ruby 2.6.7`.)

I'm going to close this, because it doesn't make sense to make this script work on a 14 year old version of Ruby and we at least now warn people the script may fail.
