### ISSUE TITLE
SSL_CERT_FILE & SSL_CERT_DIR - check for existence?

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/ruby-ssl-check#2]
I know RG has some cert files, so I'm not sure if it uses the standard files.

Regardless, on older Windows Ruby install (<= 2.3), the constants `SSL_CERT_FILE` & `SSL_CERT_DIR` will exist, but the files may not exist.  See [Appveyor Ruby Info](https://ci.appveyor.com/project/MSP-Greg/appveyor-ruby)

Hence, might a check for that be added to `check.rb`?  I'd do a PR, but you see the output a lot more than I do...

Thanks, Greg

**Comment by indirect** [comment]
Sure, the check seems reasonable to me. Feel free to open a PR.
